function myFunction() {
    let cheers = [
        "You might not believe in yourself, but know and remember that I believe in you. I always have and I always will.",
        "Who cares about the storm? Don't worry. I can't make it stop, but I can always hold your umbrella.",
        "Cheer up, my friend. God gave you those problems because He knows you are strong enough to handle and overcome them.",
        "If you fall, I'll pick you up. If I can't pick you up, then I'll just lie down and rest with you. Let's get back to the top together.",
        "I realize that I am indeed a very lucky person. I've been blessed with the most wonderful people in my life, and that includes you.",
        "It's tough now, but I believe that there is a brighter future waiting for us. You'll get through this. Trust me.",
        "Your mistakes and failures don't define who you are. Believe you can, and you'll eventually get there. I'll be there to hold you up.",
        "Whatever you do, remember that you are not alone. No matter what happens, I've always got your back.",
        "My friend, always remember that you are important and worthy of everything good in this world.",
        "Rest if you must; we're not in a hurry. You can't always function the way people expect you to.",
        "I won't ask you to act now if you don't feel like it. I'll stay by your side and wait until you are ready and choose to fight again.",
        "Did you know that you are like magic? Good things come whenever you're around.",
        "Here's what you need to remember: You are enough and you are wonderful, even on those days you feel broken and shattered.",
        "It may seem that things are hopeless right now, but I know that there's so much more in store for your future.",
        "You've always been a fighter, so I know that you'll get through this. Don't lose that strength; don't let go of that bravery.",
        "Whatever you do and whatever you choose, I will always be proud of you. Don't put yourself down.",
        "Do you know where I get my strength? From you. Your dedication is what encourages me to be the best version of myself.",
        "You are bold and courageous. You are important. No one can tell you otherwise.",
        "You are the writer of your story, and you decide your own destiny. No matter what happens, I believe you will always have the power to endure.",
        "Do you know how valuable you are? You are a gift not just to me and the people around you, but to the whole world.",
        "Let go of what is hurting you. Don't hang on to something that just keeps on dragging you down. You have me, your other friends, and your family. Hold on to us.",
        "The best is yet to come, so sit up straight and stop the tears. Whatever is happening right now is not the end.",
        "I always knew that you could do anything. After all, you are smart and ambitious. Cheer up, buddy! Nothing can stop us now.",
        "It's okay to feel down today, and perhaps even tomorrow. But always remember that you are a champion. You are amazing—never forget that.",
        "Words can't describe how proud of you I am. I am happiest whenever someone praises you, my friend.",
        "Good things come to those who wait. This is just a chapter in your life and not the whole story. Hang on a little—I'll be with you through everything.",
        "Let me know if you can't see the light anymore. I will buy a whole bunch of bulbs for you.",
        "My friend, there are so many beautiful reasons to fight for life and happiness. Keep going. Let's fight together.",
        "We all experience bad days; we all have to deal with our inner demons. When you feel like there's nothing you can do about it, know that you can always depend on me for support.",
        "Don't lose faith. It can be really hard to keep going at times, especially when you don't have enough motivation. But despite that, we should still keep our heads up.",
        "Don't thinking that there's nothing to live for. Our friends, your family, and you—your existence alone—are all worth living for.",
        "Hard times hit us all, but we survive by being strong. I don't worry about you—you're a strong and amazing person.",
        "Think of this as just another lesson that you need to learn. Life is tough, but so are you. You can't let it defeat you.",
        "We've been friends for a long time, and I know that no one can stop you from winning. So don't back down. I've got your back.",
        "Don't doubt your accomplishments. You succeeded because you worked hard for it. You are here because you deserve to be.",
    ];
    alert(cheers[Math.floor(Math.random() * cheers.length)]);
}
